version: "3"
services:
  dev:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: npm run dev
    volumes:
      - .:/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: